The one-command executable-assertion demo (v2 analogue of v1's run_demo.py). Drives the full async cycle and asserts steps (a)-(f) in order:
(a) pipes a synthetic PostToolUse(Write) event into hooks/async_launcher.py, asserts exit 0 in <2.0s + a wu-<run_id>.txt spool file, then JOINs on the pending queue reaching 2 SURFACED (detached PID can't be .wait()-ed portably);
(b) calls run_background_audit in-process with the stub judge (deterministic core): asserts the v1 oracle (2 surfaced [no-secrets-in-logs.md, timeout-on-external-calls.md], killed_by_judge==1, below_confidence==0), that read_unconsumed() returns 2 PendingFindings whose .fix round-trips RetroFix.as_dict() (8 keys) and whose .work_unit_sig==work_unit_signature(work_unit), and that a 2nd run adds 0 new SURFACED (dedup D-4);
(c) pipes UserPromptSubmit into hooks/async_inject.py, asserts valid JSON with hookEventName=='UserPromptSubmit', additionalContext containing both rule_ids + 'PROPOSAL', then CONSUMED==2 / SURFACED-current==0;
(d) a 2nd inject is silent (no additionalContext, exit 0);
(e) shells out to examples/demo/run_demo.py, asserts exit 0 + 'DEMO PASSED' marker, and that a plain v1 config with no [async] table loads with async_enabled is False / async_mode=='sync';
(f) asserts lazarus_sonar.async_.stub_judge.stub_judge_fn == examples/demo/stub_judge.py stub_judge_fn verdict-for-verdict.
Prints 'ASYNC DEMO PASSED' + exit 0 on success; 'ASYNC DEMO FAILED' + the mismatch + exit 1 on any drift. Bootstraps src/, examples/demo, and hooks/ onto sys.path so it runs on a bare checkout with no install. VERIFIED GREEN (exit 0), reproducible across consecutive runs and from both repo-root and subdir cwd.

Key design note captured in-file: both the OS-spawn path (a) and the in-process path (b) audit the SAME text the v1 Write-extractor produces (via retro_audit.extract_work_unit), giving one identical work_unit_signature so the queue dedups to exactly 2 findings; step (b) wipes the shared ledger just before its pass so its judge-accounting oracle stays deterministic regardless of whether (a)'s detached child already recorded prefer-f-strings.md as DECLINED.